// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $b from "./routes/b.tsx";
import * as $index from "./routes/index.tsx";
import * as $MyCoolIsland from "./islands/MyCoolIsland.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/b.tsx": $b,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/MyCoolIsland.tsx": $MyCoolIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
